-- Smartek databases initialization
CREATE DATABASE IF NOT EXISTS smartek_db;
CREATE DATABASE IF NOT EXISTS smartek_events;
CREATE DATABASE IF NOT EXISTS smartek_planning;
CREATE DATABASE IF NOT EXISTS training_db;
CREATE DATABASE IF NOT EXISTS offers_db;
CREATE DATABASE IF NOT EXISTS exam_db;
CREATE DATABASE IF NOT EXISTS course_db;
CREATE DATABASE IF NOT EXISTS learning_db;
CREATE DATABASE IF NOT EXISTS skill_evidence_db;
