global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'learning-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['smartek-learning:8092']

  - job_name: 'skill-evidence-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['smartek-skill-evidence:8091']

  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['smartek-auth:8081']

  - job_name: 'course-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['smartek-course:8086']

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['smartek-gateway:8090']
