apiVersion: v1
kind: Service
metadata:
  name: planning-service
  namespace: smartek
spec:
  type: NodePort
  ports:
  - port: 8083
    targetPort: 8083
    nodePort: 30083
    protocol: TCP
  selector:
    app: planning-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: planning-service
  namespace: smartek
spec:
  replicas: 1
  selector:
    matchLabels:
      app: planning-service
  template:
    metadata:
      labels:
        app: planning-service
    spec:
      containers:
      - name: planning-service
        image: wafachabbi/planning-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8083
        env:
        - name: SERVER_PORT
          value: "8083"
        - name: SPRING_APPLICATION_NAME
          value: "planning-service"
        - name: JAVA_TOOL_OPTIONS
          value: "-Xms256m -Xmx512m"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-service:3306/smartek_planning?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://eureka-server:8761/eureka/"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "768Mi"
            cpu: "500m"
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          failureThreshold: 90
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 60
          periodSeconds: 20
          failureThreshold: 10
