apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: smartek
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/smartek_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
  SPRING_DATASOURCE_USERNAME: "root"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8761/eureka/"
  SPRING_APPLICATION_NAME: "auth-service"
