global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'smartek-monitor'

scrape_configs:

  # Prometheus lui-même
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # API Gateway
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8090']

  # Auth Service
  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8081']

  # Event Service
  - job_name: 'event-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8082']

  # Planning Service
  - job_name: 'planning-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8083']

  # Training Service
  - job_name: 'training-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8084']

  # Course Service
  - job_name: 'course-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8086']

  # Exam Service
  - job_name: 'exam-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8087']
