server:
  port: 8090

spring:
  application:
    name: api-gateway
  cloud:
    config:
      enabled: false
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods: "GET,POST,PUT,DELETE,OPTIONS,PATCH"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: learning-style-service
          uri: lb://learning
          predicates:
            - Path=/api/learning-style-preferences/**
        - id: learning-service
          uri: lb://learning
          predicates:
            - Path=/api/learning-paths/**
        - id: skill-evidence-service
          uri: lb://skill-evidence-service
          predicates:
            - Path=/api/skill-evidence/**
        - id: notifications-service
          uri: lb://skill-evidence-service
          predicates:
            - Path=/api/notifications/**
        - id: offers-service
          uri: lb://offers-service
          predicates:
            - Path=/api/offers/**
        - id: applications-service
          uri: lb://offers-service
          predicates:
            - Path=/api/applications/**
        - id: interviews-service
          uri: lb://offers-service
          predicates:
            - Path=/api/interviews/**
        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/api/courses/**
        - id: course-service-websocket
          uri: lb:ws://course-service
          predicates:
            - Path=/ws/signaling/**
        - id: training-service
          uri: lb://training-service
          predicates:
            - Path=/api/trainings/**,/api/training/**
        - id: exam-service
          uri: lb://exam-service
          predicates:
            - Path=/api/exams/**
        - id: exam-questions
          uri: lb://exam-service
          predicates:
            - Path=/api/questions/**
        - id: exam-enrollments
          uri: lb://exam-service
          predicates:
            - Path=/api/exam-enrollments/**
        - id: exam-results
          uri: lb://exam-service
          predicates:
            - Path=/api/exam-results/**
        - id: exam-drafts
          uri: lb://exam-service
          predicates:
            - Path=/api/exam-drafts/**
        - id: analytics
          uri: lb://exam-service
          predicates:
            - Path=/api/analytics/trainer/*/exams
        - id: analytics-training
          uri: lb://training-service
          predicates:
            - Path=/api/analytics/trainer/*/training**,/api/analytics/trainer/*/trainings
        - id: training-enrollments
          uri: lb://training-service
          predicates:
            - Path=/api/training-enrollments/**
        - id: performance-service
          uri: lb://training-service
          predicates:
            - Path=/api/performance/**
        - id: pi-service
          uri: lb://pi-service
          predicates:
            - Path=/api/pi/**
        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/api/events/**
        - id: planning-service
          uri: lb://planning-service
          predicates:
            - Path=/api/plannings/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,gateway
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

jwt:
  secret: smartek-secret-key-for-jwt-token-generation-2024-very-secure
