sonar.projectKey=${env.SONAR_ORGANIZATION}_smartek-auth-service
sonar.projectName=Smartek Auth Service
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.exclusions=**/dto/**,**/entity/**,**/config/**,**/*Application.java
sonar.java.source=17
