server:
  port: 8082

spring:
  application:
    name: event-service
  datasource:
    url: jdbc:mysql://localhost:3306/smartek_events?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

stripe:
  secret-key: ${STRIPE_SECRET_KEY:sk_test_51TMbsyCjG1sQz26DGWWihfxkcRJ0OIVuBc4K2kvsgKohNLdWRkH4nH3nkNkwBaBPdWHLaL2vET80oSpKjsGajBz900dlw1CrcU}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET:whsec_fbfc981fba0d95b395691b00d4b6869940a039a8e08a10f5b0abf7d3360c9b8a}
  publishable-key: ${STRIPE_PUBLISHABLE_KEY:pk_test_51TMbsyCjG1sQz26DDcjxT5049h0snZozzF6Uj9yBMTMaF8IGTps0kBlSOfL5j4enSubXarobzOT9ExMhjB58VRVb006ILhoad5}
